name: secrets values in repo

on:
    workflow_dispatch:

jobs:
    deployment:
        runs-on: ubuntu-latest

        steps:
            - run: |
                echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
                echo "i_dont_exist: ${{ secrets.i_dont_exist }}"
            
            - run: |
                echo "MY_TOP_SECRET: $MY_TOP_SECRET"
              env:
                MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}